export const SET_LOADING = 'SET_LOADING'
export const GET_USERS = 'GET_USERS'
export const GET_USER = 'GET_USER'
export const SEARCH_USERS = 'SEARCH_USERS'
export const CLEAR_USERS = 'CLEAR_USERS'
export const USERNAME_CHANGED = 'USERNAME_CHANGED'
export const GET_REPOS = 'GET_REPOS'
